In [12]:
!pwd

/home/ubuntu/Berend_Gort

In [13]:
%run imports.py

%cat imports.py

import pandas as pd
import numpy as np

In [14]:
pokemon_df = pd.read_csv('Pokemon_m.csv', index_col=0, encoding='utf-8')
pokemon_df

,Name,Type_1,Type_2,Total,HP,Attack,Defense,Sp_Atk,Sp_Def,Speed,Stage,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,2,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,3,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,2,False
6,Charizard,Fire,Flying,534,78,84,78,109,85,100,3,False
7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
8,Wartortle,Water,NaN,405,59,63,80,65,80,58,2,False
9,Blastoise,Water,NaN,530,79,83,100,85,105,78,3,False
10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
11,Metapod,Bug,NaN,205,50,20,55,25,25,30,2,False
12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,3,False
13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,2,False
15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,3,False
16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,2,False
18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,3,False
19,Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False
20,Raticate,Normal,NaN,413,55,81,60,50,70,97,2,False
21,Spearow,Normal,Flying,262,40,60,30,31,31,70,1,False
22,Fearow,Normal,Flying,442,65,90,65,61,61,100,2,False
23,Ekans,Poison,NaN,288,35,60,44,40,54,55,1,False
24,Arbok,Poison,NaN,438,60,85,69,65,79,80,2,False
25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
26,Raichu,Electric,NaN,485,60,90,55,90,80,110,2,False
27,Sandshrew,Ground,NaN,300,50,75,85,20,30,40,1,False
28,Sandslash,Ground,NaN,450,75,100,110,45,55,65,2,False
29,NidoranªÛ,Poison,NaN,275,55,47,52,40,40,41,1,False
30,Nidorina,Poison,NaN,365,70,62,67,55,55,56,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...
122,Mr. Mime,Psychic,Fairy,460,40,45,65,100,120,90,1,False
123,Scyther,Bug,Flying,500,70,110,80,55,80,105,1,False
124,Jynx,Ice,Psychic,455,65,50,35,115,95,95,1,False
125,Electabuzz,Electric,NaN,490,65,83,57,95,85,105,1,False
126,Magmar,Fire,NaN,495,65,95,57,100,85,93,1,False
127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False
128,Tauros,Normal,NaN,490,75,100,95,40,70,110,1,False
129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
130,Gyarados,Water,Flying,540,95,125,79,60,100,81,2,False
131,Lapras,Water,Ice,535,130,85,80,85,95,60,1,False
132,Ditto,Normal,NaN,288,48,48,48,48,48,48,1,False
133,Eevee,Normal,NaN,325,55,55,50,45,65,55,1,False
134,Vaporeon,Water,NaN,525,130,65,60,110,95,65,2,False
135,Jolteon,Electric,NaN,525,65,65,60,110,95,130,2,False
136,Flareon,Fire,NaN,525,65,130,60,95,110,65,2,False
137,Porygon,Normal,NaN,395,65,60,70,85,75,40,1,False
138,Omanyte,Rock,Water,355,35,40,100,90,55,35,1,False
139,Omastar,Rock,Water,495,70,60,125,115,70,55,2,False
140,Kabuto,Rock,Water,355,30,80,90,55,45,55,1,False
141,Kabutops,Rock,Water,495,60,115,105,65,70,80,2,False
142,Aerodactyl,Rock,Flying,515,80,105,65,60,75,130,1,False
143,Snorlax,Normal,NaN,540,160,110,65,65,110,30,1,False
144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
147,Dratini,Dragon,NaN,300,41,64,45,50,50,50,1,False
148,Dragonair,Dragon,NaN,420,61,84,65,70,70,70,2,False
149,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,3,False
150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
151,Mew,Psychic,NaN,600,100,100,100,100,100,100,1,False

In [15]:
import sklearn
from sklearn import datasets
from sklearn import preprocessing
from sklearn import metrics
from sklearn import model_selection
from sklearn.pipeline import Pipeline
from sklearn.feature_selection  import *
from sklearn.linear_model  import *

#### custom transformer

In [17]:
transformer = preprocessing.FunctionTransformer(lambda x: x+17)
X = np.array([[0, 1], [2, 3]])
transformer.transform(X)

array([[17, 18],
       [19, 20]])

In [21]:
def my_functional_transformer_function(X):
    
    print(X)
    return X + 17

In [22]:
transformer = preprocessing.FunctionTransformer(my_functional_transformer_function)
transformer.transform(pokemon_df[ ['HP', 'Attack' , 'Defense'] ])

[[ 45  49  49]
 [ 60  62  63]
 [ 80  82  83]
 [ 39  52  43]
 [ 58  64  58]
 [ 78  84  78]
 [ 44  48  65]
 [ 59  63  80]
 [ 79  83 100]
 [ 45  30  35]
 [ 50  20  55]
 [ 60  45  50]
 [ 40  35  30]
 [ 45  25  50]
 [ 65  90  40]
 [ 40  45  40]
 [ 63  60  55]
 [ 83  80  75]
 [ 30  56  35]
 [ 55  81  60]
 [ 40  60  30]
 [ 65  90  65]
 [ 35  60  44]
 [ 60  85  69]
 [ 35  55  40]
 [ 60  90  55]
 [ 50  75  85]
 [ 75 100 110]
 [ 55  47  52]
 [ 70  62  67]
 [ 90  92  87]
 [ 46  57  40]
 [ 61  72  57]
 [ 81 102  77]
 [ 70  45  48]
 [ 95  70  73]
 [ 38  41  40]
 [ 73  76  75]
 [115  45  20]
 [140  70  45]
 [ 40  45  35]
 [ 75  80  70]
 [ 45  50  55]
 [ 60  65  70]
 [ 75  80  85]
 [ 35  70  55]
 [ 60  95  80]
 [ 60  55  50]
 [ 70  65  60]
 [ 10  55  25]
 [ 35  80  50]
 [ 40  45  35]
 [ 65  70  60]
 [ 50  52  48]
 [ 80  82  78]
 [ 40  80  35]
 [ 65 105  60]
 [ 55  70  45]
 [ 90 110  80]
 [ 40  50  40]
 [ 65  65  65]
 [ 90  95  95]
 [ 25  20  15]
 [ 40  35  30]
 [ 55  50  45]
 [ 70  80  50]
 [ 80 100  70]
 [ 90 130  80]
 [ 50  75  35]
 [ 65  90  50]
 [ 80 105  65]
 [ 40  40  35]
 [ 80  70  65]
 [ 40  80 100]
 [ 55  95 115]
 [ 80 120 130]
 [ 50  85  55]
 [ 65 100  70]
 [ 90  65  65]
 [ 95  75 110]
 [ 25  35  70]
 [ 50  60  95]
 [ 52  65  55]
 [ 35  85  45]
 [ 60 110  70]
 [ 65  45  55]
 [ 90  70  80]
 [ 80  80  50]
 [105 105  75]
 [ 30  65 100]
 [ 50  95 180]
 [ 30  35  30]
 [ 45  50  45]
 [ 60  65  60]
 [ 35  45 160]
 [ 60  48  45]
 [ 85  73  70]
 [ 30 105  90]
 [ 55 130 115]
 [ 40  30  50]
 [ 60  50  70]
 [ 60  40  80]
 [ 95  95  85]
 [ 50  50  95]
 [ 60  80 110]
 [ 50 120  53]
 [ 50 105  79]
 [ 90  55  75]
 [ 40  65  95]
 [ 65  90 120]
 [ 80  85  95]
 [105 130 120]
 [250   5   5]
 [ 65  55 115]
 [105  95  80]
 [ 30  40  70]
 [ 55  65  95]
 [ 45  67  60]
 [ 80  92  65]
 [ 30  45  55]
 [ 60  75  85]
 [ 40  45  65]
 [ 70 110  80]
 [ 65  50  35]
 [ 65  83  57]
 [ 65  95  57]
 [ 65 125 100]
 [ 75 100  95]
 [ 20  10  55]
 [ 95 125  79]
 [130  85  80]
 [ 48  48  48]
 [ 55  55  50]
 [130  65  60]
 [ 65  65  60]
 [ 65 130  60]
 [ 65  60  70]
 [ 35  40 100]
 [ 70  60 125]
 [ 30  80  90]
 [ 60 115 105]
 [ 80 105  65]
 [160 110  65]
 [ 90  85 100]
 [ 90  90  85]
 [ 90 100  90]
 [ 41  64  45]
 [ 61  84  65]
 [ 91 134  95]
 [106 110  90]
 [100 100 100]]

array([[ 62,  66,  66],
       [ 77,  79,  80],
       [ 97,  99, 100],
       [ 56,  69,  60],
       [ 75,  81,  75],
       [ 95, 101,  95],
       [ 61,  65,  82],
       [ 76,  80,  97],
       [ 96, 100, 117],
       [ 62,  47,  52],
       [ 67,  37,  72],
       [ 77,  62,  67],
       [ 57,  52,  47],
       [ 62,  42,  67],
       [ 82, 107,  57],
       [ 57,  62,  57],
       [ 80,  77,  72],
       [100,  97,  92],
       [ 47,  73,  52],
       [ 72,  98,  77],
       [ 57,  77,  47],
       [ 82, 107,  82],
       [ 52,  77,  61],
       [ 77, 102,  86],
       [ 52,  72,  57],
       [ 77, 107,  72],
       [ 67,  92, 102],
       [ 92, 117, 127],
       [ 72,  64,  69],
       [ 87,  79,  84],
       [107, 109, 104],
       [ 63,  74,  57],
       [ 78,  89,  74],
       [ 98, 119,  94],
       [ 87,  62,  65],
       [112,  87,  90],
       [ 55,  58,  57],
       [ 90,  93,  92],
       [132,  62,  37],
       [157,  87,  62],
       [ 57,  62,  52],
       [ 92,  97,  87],
       [ 62,  67,  72],
       [ 77,  82,  87],
       [ 92,  97, 102],
       [ 52,  87,  72],
       [ 77, 112,  97],
       [ 77,  72,  67],
       [ 87,  82,  77],
       [ 27,  72,  42],
       [ 52,  97,  67],
       [ 57,  62,  52],
       [ 82,  87,  77],
       [ 67,  69,  65],
       [ 97,  99,  95],
       [ 57,  97,  52],
       [ 82, 122,  77],
       [ 72,  87,  62],
       [107, 127,  97],
       [ 57,  67,  57],
       [ 82,  82,  82],
       [107, 112, 112],
       [ 42,  37,  32],
       [ 57,  52,  47],
       [ 72,  67,  62],
       [ 87,  97,  67],
       [ 97, 117,  87],
       [107, 147,  97],
       [ 67,  92,  52],
       [ 82, 107,  67],
       [ 97, 122,  82],
       [ 57,  57,  52],
       [ 97,  87,  82],
       [ 57,  97, 117],
       [ 72, 112, 132],
       [ 97, 137, 147],
       [ 67, 102,  72],
       [ 82, 117,  87],
       [107,  82,  82],
       [112,  92, 127],
       [ 42,  52,  87],
       [ 67,  77, 112],
       [ 69,  82,  72],
       [ 52, 102,  62],
       [ 77, 127,  87],
       [ 82,  62,  72],
       [107,  87,  97],
       [ 97,  97,  67],
       [122, 122,  92],
       [ 47,  82, 117],
       [ 67, 112, 197],
       [ 47,  52,  47],
       [ 62,  67,  62],
       [ 77,  82,  77],
       [ 52,  62, 177],
       [ 77,  65,  62],
       [102,  90,  87],
       [ 47, 122, 107],
       [ 72, 147, 132],
       [ 57,  47,  67],
       [ 77,  67,  87],
       [ 77,  57,  97],
       [112, 112, 102],
       [ 67,  67, 112],
       [ 77,  97, 127],
       [ 67, 137,  70],
       [ 67, 122,  96],
       [107,  72,  92],
       [ 57,  82, 112],
       [ 82, 107, 137],
       [ 97, 102, 112],
       [122, 147, 137],
       [267,  22,  22],
       [ 82,  72, 132],
       [122, 112,  97],
       [ 47,  57,  87],
       [ 72,  82, 112],
       [ 62,  84,  77],
       [ 97, 109,  82],
       [ 47,  62,  72],
       [ 77,  92, 102],
       [ 57,  62,  82],
       [ 87, 127,  97],
       [ 82,  67,  52],
       [ 82, 100,  74],
       [ 82, 112,  74],
       [ 82, 142, 117],
       [ 92, 117, 112],
       [ 37,  27,  72],
       [112, 142,  96],
       [147, 102,  97],
       [ 65,  65,  65],
       [ 72,  72,  67],
       [147,  82,  77],
       [ 82,  82,  77],
       [ 82, 147,  77],
       [ 82,  77,  87],
       [ 52,  57, 117],
       [ 87,  77, 142],
       [ 47,  97, 107],
       [ 77, 132, 122],
       [ 97, 122,  82],
       [177, 127,  82],
       [107, 102, 117],
       [107, 107, 102],
       [107, 117, 107],
       [ 58,  81,  62],
       [ 78, 101,  82],
       [108, 151, 112],
       [123, 127, 107],
       [117, 117, 117]])

#### fullscale partial transformer

In [23]:
from sklearn.base import TransformerMixin

In [168]:
class FunctionFeaturizer(TransformerMixin):
    def __init__(self, *featurizers, seventeen=17):
        self.seventeen = seventeen

    def fit(self, X, y=None):
        self.seventeen = - np.mean(X)
        return self

    def transform(self, X):
        #Do transformations
        return X+self.seventeen

In [169]:
our_transformer = FunctionFeaturizer(seventeen=19)
X = np.array([[0, 1], [2, 3]])
our_transformer.transform(X)

array([[19, 20],
       [21, 22]])

In [175]:
our_fit_transformer = our_transformer.fit(X)
our_fit_transformer

In [173]:
our_fit_transformer.transform(X)

array([[-1.5, -0.5],
       [ 0.5,  1.5]])

In [37]:
our_fit_transformer.transform(X).mean()

0.0

In [39]:
our_fit_transformer

In [38]:
our_fit_transformer.seventeen

-1.5

#### Exercise 5.1: Write a fucntional transformer that computes string of all variables in the row

In [65]:
bulbasaur = pokemon_df.iloc[0,:]
str(bulbasaur[7])

'65'

In [77]:
def my_functional_transformer_function(sample):
    string = ''
    for i in range(len(sample)):
      piece = str(sample[i])
      string = string + ' ' + piece    
    return string

In [80]:
my_functional_transformer_function(bulbasaur)

' Bulbasaur Grass Poison 318 45 49 49 65 65 45 1 False'

In [94]:
string_of_all_rows = [pokemon_df.shape[0],1]
string_of_all_rows

[151, 1]

In [96]:
string_of_all_rows = [pokemon_df.shape[0],1]
for i in range(pokemon_df.shape[0]):
    pokemon_i = pokemon_df.iloc[i,:]
    string_of_all_rows.append(my_functional_transformer_function(pokemon_i))
string_of_all_rows

[151,
 1,
 ' Bulbasaur Grass Poison 318 45 49 49 65 65 45 1 False',
 ' Ivysaur Grass Poison 405 60 62 63 80 80 60 2 False',
 ' Venusaur Grass Poison 525 80 82 83 100 100 80 3 False',
 ' Charmander Fire nan 309 39 52 43 60 50 65 1 False',
 ' Charmeleon Fire nan 405 58 64 58 80 65 80 2 False',
 ' Charizard Fire Flying 534 78 84 78 109 85 100 3 False',
 ' Squirtle Water nan 314 44 48 65 50 64 43 1 False',
 ' Wartortle Water nan 405 59 63 80 65 80 58 2 False',
 ' Blastoise Water nan 530 79 83 100 85 105 78 3 False',
 ' Caterpie Bug nan 195 45 30 35 20 20 45 1 False',
 ' Metapod Bug nan 205 50 20 55 25 25 30 2 False',
 ' Butterfree Bug Flying 395 60 45 50 90 80 70 3 False',
 ' Weedle Bug Poison 195 40 35 30 20 20 50 1 False',
 ' Kakuna Bug Poison 205 45 25 50 25 25 35 2 False',
 ' Beedrill Bug Poison 395 65 90 40 45 80 75 3 False',
 ' Pidgey Normal Flying 251 40 45 40 35 35 56 1 False',
 ' Pidgeotto Normal Flying 349 63 60 55 50 50 71 2 False',
 ' Pidgeot Normal Flying 479 83 80 75 70 70 101 3 False',
 ' Rattata Normal nan 253 30 56 35 25 35 72 1 False',
 ' Raticate Normal nan 413 55 81 60 50 70 97 2 False',
 ' Spearow Normal Flying 262 40 60 30 31 31 70 1 False',
 ' Fearow Normal Flying 442 65 90 65 61 61 100 2 False',
 ' Ekans Poison nan 288 35 60 44 40 54 55 1 False',
 ' Arbok Poison nan 438 60 85 69 65 79 80 2 False',
 ' Pikachu Electric nan 320 35 55 40 50 50 90 1 False',
 ' Raichu Electric nan 485 60 90 55 90 80 110 2 False',
 ' Sandshrew Ground nan 300 50 75 85 20 30 40 1 False',
 ' Sandslash Ground nan 450 75 100 110 45 55 65 2 False',
 ' Nidoran\x89ªÛ Poison nan 275 55 47 52 40 40 41 1 False',
 ' Nidorina Poison nan 365 70 62 67 55 55 56 2 False',
 ' Nidoqueen Poison Ground 505 90 92 87 75 85 76 3 False',
 ' Nidoran\x89ªâ Poison nan 273 46 57 40 40 40 50 1 False',
 ' Nidorino Poison nan 365 61 72 57 55 55 65 2 False',
 ' Nidoking Poison Ground 505 81 102 77 85 75 85 3 False',
 ' Clefairy Fairy nan 323 70 45 48 60 65 35 1 False',
 ' Clefable Fairy nan 483 95 70 73 95 90 60 2 False',
 ' Vulpix Fire nan 299 38 41 40 50 65 65 1 False',
 ' Ninetales Fire nan 505 73 76 75 81 100 100 2 False',
 ' Jigglypuff Normal Fairy 270 115 45 20 45 25 20 1 False',
 ' Wigglytuff Normal Fairy 435 140 70 45 85 50 45 2 False',
 ' Zubat Poison Flying 245 40 45 35 30 40 55 1 False',
 ' Golbat Poison Flying 455 75 80 70 65 75 90 2 False',
 ' Oddish Grass Poison 320 45 50 55 75 65 30 1 False',
 ' Gloom Grass Poison 395 60 65 70 85 75 40 2 False',
 ' Vileplume Grass Poison 490 75 80 85 110 90 50 3 False',
 ' Paras Bug Grass 285 35 70 55 45 55 25 1 False',
 ' Parasect Bug Grass 405 60 95 80 60 80 30 2 False',
 ' Venonat Bug Poison 305 60 55 50 40 55 45 1 False',
 ' Venomoth Bug Poison 450 70 65 60 90 75 90 2 False',
 ' Diglett Ground nan 265 10 55 25 35 45 95 1 False',
 ' Dugtrio Ground nan 405 35 80 50 50 70 120 2 False',
 ' Meowth Normal nan 290 40 45 35 40 40 90 1 False',
 ' Persian Normal nan 440 65 70 60 65 65 115 2 False',
 ' Psyduck Water nan 320 50 52 48 65 50 55 1 False',
 ' Golduck Water nan 500 80 82 78 95 80 85 2 False',
 ' Mankey Fighting nan 305 40 80 35 35 45 70 1 False',
 ' Primeape Fighting nan 455 65 105 60 60 70 95 2 False',
 ' Growlithe Fire nan 350 55 70 45 70 50 60 1 False',
 ' Arcanine Fire nan 555 90 110 80 100 80 95 2 False',
 ' Poliwag Water nan 300 40 50 40 40 40 90 1 False',
 ' Poliwhirl Water nan 385 65 65 65 50 50 90 2 False',
 ' Poliwrath Water Fighting 510 90 95 95 70 90 70 3 False',
 ' Abra Psychic nan 310 25 20 15 105 55 90 1 False',
 ' Kadabra Psychic nan 400 40 35 30 120 70 105 2 False',
 ' Alakazam Psychic nan 500 55 50 45 135 95 120 3 False',
 ' Machop Fighting nan 305 70 80 50 35 35 35 1 False',
 ' Machoke Fighting nan 405 80 100 70 50 60 45 2 False',
 ' Machamp Fighting nan 505 90 130 80 65 85 55 3 False',
 ' Bellsprout Grass Poison 300 50 75 35 70 30 40 1 False',
 ' Weepinbell Grass Poison 390 65 90 50 85 45 55 2 False',
 ' Victreebel Grass Poison 490 80 105 65 100 70 70 3 False',
 ' Tentacool Water Poison 335 40 40 35 50 100 70 1 False',
 ' Tentacruel Water Poison 515 80 70 65 80 120 100 2 False',
 ' Geodude Rock Ground 300 40 80 100 30 30 20 1 False',
 ' Graveler Rock Ground 390 55 95 115 45 45 35 2 False',
 ' Golem Rock Ground 495 80 120 130 55 65 45 3 False',
 ' Ponyta Fire nan 410 50 85 55 65 65 90 1 False',
 ' Rapidash Fire nan 500 65 100 70 80 80 105 2 False',
 ' Slowpoke Water Psychic 315 90 65 65 40 40 15 1 False',
 ' Slowbro Water Psychic 490 95 75 110 100 80 30 2 False',
 ' Magnemite Electric Steel 325 25 35 70 95 55 45 1 False',
 ' Magneton Electric Steel 465 50 60 95 120 70 70 2 False',
 " Farfetch'd Normal Flying 352 52 65 55 58 62 60 1 False",
 ' Doduo Normal Flying 310 35 85 45 35 35 75 1 False',
 ' Dodrio Normal Flying 460 60 110 70 60 60 100 2 False',
 ' Seel Water nan 325 65 45 55 45 70 45 1 False',
 ' Dewgong Water Ice 475 90 70 80 70 95 70 2 False',
 ' Grimer Poison nan 325 80 80 50 40 50 25 1 False',
 ' Muk Poison nan 500 105 105 75 65 100 50 2 False',
 ' Shellder Water nan 305 30 65 100 45 25 40 1 False',
 ' Cloyster Water Ice 525 50 95 180 85 45 70 2 False',
 ' Gastly Ghost Poison 310 30 35 30 100 35 80 1 False',
 ' Haunter Ghost Poison 405 45 50 45 115 55 95 2 False',
 ' Gengar Ghost Poison 500 60 65 60 130 75 110 3 False',
 ' Onix Rock Ground 385 35 45 160 30 45 70 1 False',
 ' Drowzee Psychic nan 328 60 48 45 43 90 42 1 False',
 ' Hypno Psychic nan 483 85 73 70 73 115 67 2 False',
 ' Krabby Water nan 325 30 105 90 25 25 50 1 False',
 ' Kingler Water nan 475 55 130 115 50 50 75 2 False',
 ' Voltorb Electric nan 330 40 30 50 55 55 100 1 False',
 ' Electrode Electric nan 480 60 50 70 80 80 140 2 False',
 ' Exeggcute Grass Psychic 325 60 40 80 60 45 40 1 False',
 ' Exeggutor Grass Psychic 520 95 95 85 125 65 55 2 False',
 ' Cubone Ground nan 320 50 50 95 40 50 35 1 False',
 ' Marowak Ground nan 425 60 80 110 50 80 45 2 False',
 ' Hitmonlee Fighting nan 455 50 120 53 35 110 87 1 False',
 ' Hitmonchan Fighting nan 455 50 105 79 35 110 76 1 False',
 ' Lickitung Normal nan 385 90 55 75 60 75 30 1 False',
 ' Koffing Poison nan 340 40 65 95 60 45 35 1 False',
 ' Weezing Poison nan 490 65 90 120 85 70 60 2 False',
 ' Rhyhorn Ground Rock 345 80 85 95 30 30 25 1 False',
 ' Rhydon Ground Rock 485 105 130 120 45 45 40 2 False',
 ' Chansey Normal nan 450 250 5 5 35 105 50 1 False',
 ' Tangela Grass nan 435 65 55 115 100 40 60 1 False',
 ' Kangaskhan Normal nan 490 105 95 80 40 80 90 1 False',
 ' Horsea Water nan 295 30 40 70 70 25 60 1 False',
 ' Seadra Water nan 440 55 65 95 95 45 85 2 False',
 ' Goldeen Water nan 320 45 67 60 35 50 63 1 False',
 ' Seaking Water nan 450 80 92 65 65 80 68 2 False',
 ' Staryu Water nan 340 30 45 55 70 55 85 1 False',
 ' Starmie Water Psychic 520 60 75 85 100 85 115 2 False',
 ' Mr. Mime Psychic Fairy 460 40 45 65 100 120 90 1 False',
 ' Scyther Bug Flying 500 70 110 80 55 80 105 1 False',
 ' Jynx Ice Psychic 455 65 50 35 115 95 95 1 False',
 ' Electabuzz Electric nan 490 65 83 57 95 85 105 1 False',
 ' Magmar Fire nan 495 65 95 57 100 85 93 1 False',
 ' Pinsir Bug nan 500 65 125 100 55 70 85 1 False',
 ' Tauros Normal nan 490 75 100 95 40 70 110 1 False',
 ' Magikarp Water nan 200 20 10 55 15 20 80 1 False',
 ' Gyarados Water Flying 540 95 125 79 60 100 81 2 False',
 ' Lapras Water Ice 535 130 85 80 85 95 60 1 False',
 ' Ditto Normal nan 288 48 48 48 48 48 48 1 False',
 ' Eevee Normal nan 325 55 55 50 45 65 55 1 False',
 ' Vaporeon Water nan 525 130 65 60 110 95 65 2 False',
 ' Jolteon Electric nan 525 65 65 60 110 95 130 2 False',
 ' Flareon Fire nan 525 65 130 60 95 110 65 2 False',
 ' Porygon Normal nan 395 65 60 70 85 75 40 1 False',
 ' Omanyte Rock Water 355 35 40 100 90 55 35 1 False',
 ' Omastar Rock Water 495 70 60 125 115 70 55 2 False',
 ' Kabuto Rock Water 355 30 80 90 55 45 55 1 False',
 ' Kabutops Rock Water 495 60 115 105 65 70 80 2 False',
 ' Aerodactyl Rock Flying 515 80 105 65 60 75 130 1 False',
 ' Snorlax Normal nan 540 160 110 65 65 110 30 1 False',
 ' Articuno Ice Flying 580 90 85 100 95 125 85 1 True',
 ' Zapdos Electric Flying 580 90 90 85 125 90 100 1 True',
 ' Moltres Fire Flying 580 90 100 90 125 85 90 1 True',
 ' Dratini Dragon nan 300 41 64 45 50 50 50 1 False',
 ' Dragonair Dragon nan 420 61 84 65 70 70 70 2 False',
 ' Dragonite Dragon Flying 600 91 134 95 100 100 80 3 False',
 ' Mewtwo Psychic nan 680 106 110 90 154 90 130 1 True',
 ' Mew Psychic nan 600 100 100 100 100 100 100 1 False']

#### Exercise 5.2: Write a custom transformer for titanic dataset that extracts Mrs. from the name of passegner

In [97]:
titanic_df = pd.read_csv('titanic.csv')
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,0,2,"Giles, Mr. Frederick Edward",male,21.0,1,0,28134,11.5000,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
870,871,0,3,"Balkic, Mr. Cerin",male,26.0,0,0,349248,7.8958,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [128]:
list_of_names = titanic_df['Name']
list_of_names[0]

res = list_of_names[8].split() 

res

#res == 'Mrs.'

['Johnson,', 'Mrs.', 'Oscar', 'W', '(Elisabeth', 'Vilhelmina', 'Berg)']

In [142]:
import re

def my_functional_transformer_function(name): 
    separate_strings= name.split()   
    for i in range(len(separate_strings)):
        if separate_strings[i] == 'Mrs.':
            index_Mrs = i
        else:
            pass      
    return print('In the name |', name, '| the', index_Mrs + 1 ,'nd', 'word contains Mrs.')

In [143]:
my_functional_transformer_function(list_of_names[8])

In the name | Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg) | the 2 nd word contains Mrs.

#### custom classifier

In [144]:
from sklearn.base import BaseEstimator, ClassifierMixin

In [167]:
class MyClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, lr=0.2):
        pass
        
    def fit(self, X, y):
        pass

    def predict(self, X):
    
        pass

#### Exercise 5.3: Write a custom classifer that scans training dataset, computes average values and outputs it as prediction

In [153]:
pokemon_df

,Name,Type_1,Type_2,Total,HP,Attack,Defense,Sp_Atk,Sp_Def,Speed,Stage,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,2,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,3,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,2,False
6,Charizard,Fire,Flying,534,78,84,78,109,85,100,3,False
7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
8,Wartortle,Water,NaN,405,59,63,80,65,80,58,2,False
9,Blastoise,Water,NaN,530,79,83,100,85,105,78,3,False
10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
11,Metapod,Bug,NaN,205,50,20,55,25,25,30,2,False
12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,3,False
13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,2,False
15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,3,False
16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,2,False
18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,3,False
19,Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False
20,Raticate,Normal,NaN,413,55,81,60,50,70,97,2,False
21,Spearow,Normal,Flying,262,40,60,30,31,31,70,1,False
22,Fearow,Normal,Flying,442,65,90,65,61,61,100,2,False
23,Ekans,Poison,NaN,288,35,60,44,40,54,55,1,False
24,Arbok,Poison,NaN,438,60,85,69,65,79,80,2,False
25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
26,Raichu,Electric,NaN,485,60,90,55,90,80,110,2,False
27,Sandshrew,Ground,NaN,300,50,75,85,20,30,40,1,False
28,Sandslash,Ground,NaN,450,75,100,110,45,55,65,2,False
29,NidoranªÛ,Poison,NaN,275,55,47,52,40,40,41,1,False
30,Nidorina,Poison,NaN,365,70,62,67,55,55,56,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...
122,Mr. Mime,Psychic,Fairy,460,40,45,65,100,120,90,1,False
123,Scyther,Bug,Flying,500,70,110,80,55,80,105,1,False
124,Jynx,Ice,Psychic,455,65,50,35,115,95,95,1,False
125,Electabuzz,Electric,NaN,490,65,83,57,95,85,105,1,False
126,Magmar,Fire,NaN,495,65,95,57,100,85,93,1,False
127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False
128,Tauros,Normal,NaN,490,75,100,95,40,70,110,1,False
129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
130,Gyarados,Water,Flying,540,95,125,79,60,100,81,2,False
131,Lapras,Water,Ice,535,130,85,80,85,95,60,1,False
132,Ditto,Normal,NaN,288,48,48,48,48,48,48,1,False
133,Eevee,Normal,NaN,325,55,55,50,45,65,55,1,False
134,Vaporeon,Water,NaN,525,130,65,60,110,95,65,2,False
135,Jolteon,Electric,NaN,525,65,65,60,110,95,130,2,False
136,Flareon,Fire,NaN,525,65,130,60,95,110,65,2,False
137,Porygon,Normal,NaN,395,65,60,70,85,75,40,1,False
138,Omanyte,Rock,Water,355,35,40,100,90,55,35,1,False
139,Omastar,Rock,Water,495,70,60,125,115,70,55,2,False
140,Kabuto,Rock,Water,355,30,80,90,55,45,55,1,False
141,Kabutops,Rock,Water,495,60,115,105,65,70,80,2,False
142,Aerodactyl,Rock,Flying,515,80,105,65,60,75,130,1,False
143,Snorlax,Normal,NaN,540,160,110,65,65,110,30,1,False
144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
147,Dratini,Dragon,NaN,300,41,64,45,50,50,50,1,False
148,Dragonair,Dragon,NaN,420,61,84,65,70,70,70,2,False
149,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,3,False
150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
151,Mew,Psychic,NaN,600,100,100,100,100,100,100,1,False

In [162]:

numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
pokemon_df_numeric = pokemon_df.select_dtypes(include=numerics)
pokemon_df_numeric

     Total   HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Stage
#
1      318   45      49       49      65      65     45      1
2      405   60      62       63      80      80     60      2
3      525   80      82       83     100     100     80      3
4      309   39      52       43      60      50     65      1
5      405   58      64       58      80      65     80      2
6      534   78      84       78     109      85    100      3
7      314   44      48       65      50      64     43      1
8      405   59      63       80      65      80     58      2
9      530   79      83      100      85     105     78      3
10     195   45      30       35      20      20     45      1
11     205   50      20       55      25      25     30      2
12     395   60      45       50      90      80     70      3
13     195   40      35       30      20      20     50      1
14     205   45      25       50      25      25     35      2
15     395   65      90       40      45      80     75      3
16     251   40      45       40      35      35     56      1
17     349   63      60       55      50      50     71      2
18     479   83      80       75      70      70    101      3
19     253   30      56       35      25      35     72      1
20     413   55      81       60      50      70     97      2
21     262   40      60       30      31      31     70      1
22     442   65      90       65      61      61    100      2
23     288   35      60       44      40      54     55      1
24     438   60      85       69      65      79     80      2
25     320   35      55       40      50      50     90      1
26     485   60      90       55      90      80    110      2
27     300   50      75       85      20      30     40      1
28     450   75     100      110      45      55     65      2
29     275   55      47       52      40      40     41      1
30     365   70      62       67      55      55     56      2
..     ...  ...     ...      ...     ...     ...    ...    ...
122    460   40      45       65     100     120     90      1
123    500   70     110       80      55      80    105      1
124    455   65      50       35     115      95     95      1
125    490   65      83       57      95      85    105      1
126    495   65      95       57     100      85     93      1
127    500   65     125      100      55      70     85      1
128    490   75     100       95      40      70    110      1
129    200   20      10       55      15      20     80      1
130    540   95     125       79      60     100     81      2
131    535  130      85       80      85      95     60      1
132    288   48      48       48      48      48     48      1
133    325   55      55       50      45      65     55      1
134    525  130      65       60     110      95     65      2
135    525   65      65       60     110      95    130      2
136    525   65     130       60      95     110     65      2
137    395   65      60       70      85      75     40      1
138    355   35      40      100      90      55     35      1
139    495   70      60      125     115      70     55      2
140    355   30      80       90      55      45     55      1
141    495   60     115      105      65      70     80      2
142    515   80     105       65      60      75    130      1
143    540  160     110       65      65     110     30      1
144    580   90      85      100      95     125     85      1
145    580   90      90       85     125      90    100      1
146    580   90     100       90     125      85     90      1
147    300   41      64       45      50      50     50      1
148    420   61      84       65      70      70     70      2
149    600   91     134       95     100     100     80      3
150    680  106     110       90     154      90    130      1
151    600  100     100      100     100     100    100      1

[151 rows x 8 columns]

In [144]:
from sklearn.base import BaseEstimator, ClassifierMixin

In [197]:
class MyClass:  
    def __init__(self, my_dataframe):
        numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64'] 
        self.my_dataframe = my_dataframe
        self.numeric_df = self.my_dataframe.select_dtypes(include=numerics)  
        
    def fit(self, X, y):
        pass

    def predict(self, X):
        pass

In [199]:
a = MyClass(pokemon_df)
a.numeric_df

     Total   HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Stage
#
1      318   45      49       49      65      65     45      1
2      405   60      62       63      80      80     60      2
3      525   80      82       83     100     100     80      3
4      309   39      52       43      60      50     65      1
5      405   58      64       58      80      65     80      2
6      534   78      84       78     109      85    100      3
7      314   44      48       65      50      64     43      1
8      405   59      63       80      65      80     58      2
9      530   79      83      100      85     105     78      3
10     195   45      30       35      20      20     45      1
11     205   50      20       55      25      25     30      2
12     395   60      45       50      90      80     70      3
13     195   40      35       30      20      20     50      1
14     205   45      25       50      25      25     35      2
15     395   65      90       40      45      80     75      3
16     251   40      45       40      35      35     56      1
17     349   63      60       55      50      50     71      2
18     479   83      80       75      70      70    101      3
19     253   30      56       35      25      35     72      1
20     413   55      81       60      50      70     97      2
21     262   40      60       30      31      31     70      1
22     442   65      90       65      61      61    100      2
23     288   35      60       44      40      54     55      1
24     438   60      85       69      65      79     80      2
25     320   35      55       40      50      50     90      1
26     485   60      90       55      90      80    110      2
27     300   50      75       85      20      30     40      1
28     450   75     100      110      45      55     65      2
29     275   55      47       52      40      40     41      1
30     365   70      62       67      55      55     56      2
..     ...  ...     ...      ...     ...     ...    ...    ...
122    460   40      45       65     100     120     90      1
123    500   70     110       80      55      80    105      1
124    455   65      50       35     115      95     95      1
125    490   65      83       57      95      85    105      1
126    495   65      95       57     100      85     93      1
127    500   65     125      100      55      70     85      1
128    490   75     100       95      40      70    110      1
129    200   20      10       55      15      20     80      1
130    540   95     125       79      60     100     81      2
131    535  130      85       80      85      95     60      1
132    288   48      48       48      48      48     48      1
133    325   55      55       50      45      65     55      1
134    525  130      65       60     110      95     65      2
135    525   65      65       60     110      95    130      2
136    525   65     130       60      95     110     65      2
137    395   65      60       70      85      75     40      1
138    355   35      40      100      90      55     35      1
139    495   70      60      125     115      70     55      2
140    355   30      80       90      55      45     55      1
141    495   60     115      105      65      70     80      2
142    515   80     105       65      60      75    130      1
143    540  160     110       65      65     110     30      1
144    580   90      85      100      95     125     85      1
145    580   90      90       85     125      90    100      1
146    580   90     100       90     125      85     90      1
147    300   41      64       45      50      50     50      1
148    420   61      84       65      70      70     70      2
149    600   91     134       95     100     100     80      3
150    680  106     110       90     154      90    130      1
151    600  100     100      100     100     100    100      1

[151 rows x 8 columns]

#### Exercise 5.4: Write custom transofrmer that extracts only string features

In [101]:
class FunctionFeaturizer(TransformerMixin):
    def __init__(self, *featurizers, seventeen=17):
        self.seventeen = seventeen

    def fit(self, X, y=None):
        self.feature_type = type(X)
        return self

    def transform(self, X):
        #Do transformations
        if self.feature_type == str:
            return X

#### Exercise 5.5: Write custom transofrmer that extracts only float features